name: Ambiente de produção - agenciadreamup.com.br - Versão Composer Install Edition
on:
  push:
    branches:
      - main

jobs:
  wp:
    name: Build do WP
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        
      - name: Verificando o cache dos pacotes do Composer
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          
      - name: Executando composer install para dependências do Wordpress
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GITHUB_TOKEN }}"}}'
        uses: php-actions/composer@v5
        with:
          php_version: 8.2
          version: 2
          dev: no
          args: -o --ignore-platform-reqs -d ./

      - name: Remove o tema
        run: sudo rm -rf ${{ github.workspace }}/wp-content/themes/agenciadreamup
      
      - name: Copiando arquivos para ambiente de produção
        uses: Burnett01/rsync-deployments@5.2.1
        with:
          switches: --chmod='D755,F644' --chown='www-data:www-data' --no-perms --rsync-path='/usr/bin/sudo /usr/bin/rsync' -O --exclude=.git/ --exclude=.env --delete -Prltvz
          remote_path: /var/www/agenciadreamup.com.br/htdocs
          remote_host: ${{ secrets.SSH_DEV_DEPLOY_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.SSH_DEV_DEPLOY_USER }}
          remote_key: ${{ secrets.SSH_DEV_DEPLOY_KEY }}

  temaBuild:
    name: Build do Tema
    runs-on: ubuntu-22.04
    needs: wp
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        
      - name: Executando composer install no tema
        working-directory: ${{ github.workspace }}/wp-content/themes/agenciadreamup
        run: composer install

      - name: Setup do NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Removendo node_modules do tema
        working-directory: ${{ github.workspace }}/wp-content/themes/agenciadreamup
        run: rm -rf node_modules

      - name: Executando yarn cache clean no tema
        working-directory: ${{ github.workspace }}/wp-content/themes/agenciadreamup
        run: yarn cache clean

      - name: Executando yarn install no tema
        working-directory: ${{ github.workspace }}/wp-content/themes/agenciadreamup
        run: yarn install

      - name: Executando npm install no tema
        working-directory: ${{ github.workspace }}/wp-content/themes/agenciadreamup
        run: npm install
    
      - name: Executando yarn repl no tema
        working-directory: ${{ github.workspace }}/wp-content/themes/agenciadreamup
        run: yarn repl
  
      - name: Executando yarn view no tema
        working-directory: ${{ github.workspace }}/wp-content/themes/agenciadreamup
        run: yarn view
        
      - name: Executando yarn doctor no tema
        working-directory: ${{ github.workspace }}/wp-content/themes/agenciadreamup
        run: yarn doctor
        
      - name: Executando yarn build no tema
        working-directory: ${{ github.workspace }}/wp-content/themes/agenciadreamup
        run: yarn build

      - name: Remove arquivos do WP
        run: sudo rm -rf ${{ github.workspace }}/composer.json && sudo rm -rf ${{ github.workspace }}/composer.lock && sudo rm -rf ${{ github.workspace }}/yarn.lock && sudo rm -rf ${{ github.workspace }}/.gitignore && sudo rm -rf ${{ github.workspace }}/wp-content/ewww/ && sudo rm -rf ${{ github.workspace }}/wp-content/languages/ && sudo rm -rf ${{ github.workspace }}/wp-content/plugins/ && sudo rm -rf ${{ github.workspace }}/wp-content/uploads/ && sudo rm -rf ${{ github.workspace }}/wp-content/wp-rocket-config/ && sudo rm -rf ${{ github.workspace }}/wp-content/advanced-cache.php

      - name: Copiando arquivos para ambiente de produção
        uses: Burnett01/rsync-deployments@5.2.1
        with:
          switches: --chmod='D755,F644' --chown='www-data:www-data' --no-perms --rsync-path='/usr/bin/sudo /usr/bin/rsync' -O --exclude=.git/ --exclude=.env -Prltvz
          remote_path: /var/www/agenciadreamup.com.br/htdocs
          remote_host: ${{ secrets.SSH_DEV_DEPLOY_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.SSH_DEV_DEPLOY_USER }}
          remote_key: ${{ secrets.SSH_DEV_DEPLOY_KEY }}
